--- #YAML:1.0
name:               CGI-Application-Plugin-AB
version:            0.4
abstract:           A/B testing for CGI::Application-based applications.
author:
    - Steve Kemp <steve@steve.org.uk>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:    0
    Test::NoTabs:  0
    Test::Pod:     0
requires:
    CGI::Application:  0
    perl:              5.008
    Redis:             0
resources:
    bugtracker:  https://github.com/skx/CGI--Application--Plugin--AB/issues
    GitMirror:   http://git.steve.org.uk/cpan/CGI--Application--Plugin--AB
    homepage:    https://github.com/skx/CGI--Application--Plugin--AB/
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/skx/CGI--Application--Plugin--AB.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
